SELECT CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(current_timestamp());

SELECT DAY(current_timestamp());
SELECT DAYNAME(current_timestamp());

SELECT month(current_timestamp());

SELECT MONTHNAME(current_timestamp());

SELECT DATEDIFF(current_timestamp(), '2019-01-01') AS RESULTADO;

SELECT DATEDIFF(current_timestamp(), '1995-10-16') AS RESULTADO;

SELECT CURRENT_TIMESTAMP() AS DIA_HOJE
, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES
, YEAR(DATA_VENDA) AS ANO FROM NOTAS_FISCAIS;

SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes;
