use sucos;

alter table tbcliente add primary key (CPF);

alter table tbcliente add column (DATA_NASCIMENTO DATE);

INSERT INTO tbcliente(
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO,
 LIMITE_CREDITO, VOLUME_COMPRA, PRIMIERO_COMPRA, DATA_NASCIMENTO)
 VALUES ('00388934505', 'João da Silva', 'Rua projetada A número 10', '', 'VILA ROMAN', 'CARATINGA', 'AMAZONAS', '2222222', 30, 'M',
 10000.00, 2000, 0, '1995-10-16');

select * from tbcliente;

create table tbCliente (
CPF VARCHAR(11),
 NOME VARCHAR(100),
 ENDERECO1 VARCHAR(150),
 ENDERECO2 VARCHAR(150),
 BAIRRO VARCHAR(50),
 CIDADE VARCHAR(50),
 ESTADO VARCHAR(50),
 CEP VARCHAR(8),
 IDADE SMALLINT,
 SEXO VARCHAR(1),
 LIMITE_CREDITO FLOAT,
 VOLUME_COMPRA FLOAT,
 PRIMIERO_COMPRA BIT,
 DATA_NASCIMENTO DATE);
 
 SELECT * FROM tbcliente;

alter table tbcliente add primary key (CPF);

INSERT INTO tbcliente(
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO,
 LIMITE_CREDITO, VOLUME_COMPRA, PRIMIERO_COMPRA, DATA_NASCIMENTO)
 VALUES ('00388934505', 'João da Silva', 'Rua projetada A número 10', '', 'VILA ROMAN', 'CARATINGA', 'AMAZONAS', '2222222', 30, 'M',
 10000.00, 2000, 0, '1995-10-16');
